### ISSUE TITLE
Tracking Issue: road to v0.1.0

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/js-libp2p-webtransport#1]
Required Changes across js-libp2p:
  - [x] Update chainsafe noise impl: https://github.com/ChainSafe/js-libp2p-noise/pull/215
  - [x] https://github.com/libp2p/js-libp2p-interfaces/pull/292
  - [x] https://github.com/libp2p/js-libp2p-interfaces/pull/290
  - [x] https://github.com/libp2p/js-libp2p-interfaces/pull/293
  - [x] https://github.com/libp2p/js-libp2p/pull/1395
  - [x] https://github.com/libp2p/js-libp2p-components/pull/19
  - [x] https://github.com/libp2p/js-libp2p/pull/1411
  - [x] https://github.com/libp2p/js-libp2p/pull/1424 (not required, but would greatly improve the interop between js-libp2p <-> go-libp2p)

In this repo:
  - [x] Have @achingbrain review this code
  - [x] Get tests setup and passing
  - [x] Publish on npm: https://www.npmjs.com/package/@libp2p/webtransport
  - [x] Example works with just published packaes (no local files)

**Comment by MarcoPolo** [comment]
As much as possible. The only extra requirement we have here is that we need to have Go available for the test as it’s the only thing that has a webtransport server.

**Comment by achingbrain** [comment]
When the version of go-libp2p with the server gets rolled up to kubo, we can install it as a dep from npm via the [go-ipfs](https://www.npmjs.com/package/go-ipfs) module.

This obviously brings a lot of extra code with it that's not necessary - maybe another reason to resurrect [go-libp2p-daemon](https://github.com/libp2p/go-libp2p-daemon)?

**Comment by MarcoPolo** [comment]
That seems like overkill. We just need the go compiler. Maybe we can extend the normal ci template to include the go runtime. 

Ideally each repo includes its environment while still sharing with the gh action yaml.

**Comment by achingbrain** [comment]
Ah, sorry - I misread the requirement, just go, not go-libp2p.  Yep, can add go to the ci runtime in the first instance, and maybe later we can also implement a [node js listener](https://github.com/libp2p/js-libp2p-webtransport/issues/7).

**Comment by MarcoPolo** [comment]
Tracking JS test customization here: https://github.com/protocol/.github/issues/403. I don't think this is a blocker for v0.1.0, since we can manually keep these in sync and easily transition once #403 is implemented.

**Comment by MarcoPolo** [comment]
This is done! Closing this issue since we've already overdelivered by having a v1.0.2 on npm. https://www.npmjs.com/package/@libp2p/webtransport

Thanks all for the help in various js-libp2p repos \o/
